import React, { useState, useEffect, useCallback, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/lib/supabase";
import { Sidebar } from "@/components/Sidebar";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertTitle, AlertDescription } from "@/components/ui/alert";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
} from "@/components/ui/collapsible";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Upload,
  FileCheck,
  Loader2,
  AlertCircle,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  ChevronDown,
  ArrowRight,
} from "lucide-react";

// ─── Types ──────────────────────────────────────────────────────────────────

interface StatusCounts {
  complete: number;
  pending_ap_entry: number;
  no_invoice_submitted: number;
}

interface ParsedCSVRow {
  internalNumber: string;
  invoiceDate: string;
  invoiceNo: string;
  vendorName: string;
  jobsValue: string;
  grossTotal: string;
  invoiceStatus: string;
  paymentStatus: string;
  paymentDueDate: string;
  taxAmount: string;
  branchName: string;
  netTotalCAD: string;
  grossTotalCAD: string;
}

interface MatchSummary {
  csvRowsFound: number;
  willBeUpdated: number;
  alreadyComplete: number;
  notInDB: number;
}

interface PreviewRow {
  invoiceNo: string;
  vendorName: string;
  invoiceDate: string;
  amountCAD: string;
  matched: boolean;
}

interface BackfillResult {
  success: boolean;
  csv_rows_parsed: number;
  csv_unique_invoice_numbers: number;
  db_pending_records: number;
  matched: number;
  updated: number;
  unmatched: number;
  errors: number;
  unmatched_sample: string[];
  error?: string;
}

type PageState = "upload" | "preview" | "running" | "results";

// ─── CSV Parsing ────────────────────────────────────────────────────────────

const EXPECTED_HEADERS = [
  "Internal Number",
  "Invoice Date (Final)",
  "Invoice No.",
  "Vendor > Name",
  "Jobs Value",
  "Gross Total",
  "Invoice Status",
  "Payment Status",
  "Payment Due Date",
  "Tax Amount",
  "Accounting Contact Person > Vendor > Branch > Name",
  "Net Total [CAD]",
  "Gross Total [CAD]",
];

function parseCSV(text: string): { rows: ParsedCSVRow[]; error?: string } {
  const lines = text.split("\n");

  // Skip line 1 ("Generated by XTRF on...") and line 2 (blank)
  // Line 3 is headers, Lines 4+ are data
  if (lines.length < 4) {
    return { rows: [], error: "CSV file is too short to contain valid data" };
  }

  const headerLine = lines[2].trim();

  // Validate it looks like the XTRF export
  if (
    !headerLine.includes("Internal Number") ||
    !headerLine.includes("Invoice No.")
  ) {
    return {
      rows: [],
      error: "This doesn't look like an XTRF Vendor Invoice export",
    };
  }

  const rows: ParsedCSVRow[] = [];

  for (let i = 3; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    const fields = parseCSVLine(line);
    if (fields.length < 13) continue;

    rows.push({
      internalNumber: fields[0]?.trim() || "",
      invoiceDate: fields[1]?.trim() || "",
      invoiceNo: fields[2]?.trim() || "",
      vendorName: fields[3]?.trim() || "",
      jobsValue: fields[4]?.trim() || "",
      grossTotal: fields[5]?.trim() || "",
      invoiceStatus: fields[6]?.trim() || "",
      paymentStatus: fields[7]?.trim() || "",
      paymentDueDate: fields[8]?.trim() || "",
      taxAmount: fields[9]?.trim() || "",
      branchName: fields[10]?.trim() || "",
      netTotalCAD: fields[11]?.trim() || "",
      grossTotalCAD: fields[12]?.trim() || "",
    });
  }

  return { rows };
}

function parseCSVLine(line: string): string[] {
  const fields: string[] = [];
  let current = "";
  let inQuotes = false;

  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ",") {
        fields.push(current);
        current = "";
      } else {
        current += char;
      }
    }
  }
  fields.push(current);
  return fields;
}

function formatCurrency(value: string): string {
  const num = parseFloat(value);
  if (isNaN(num)) return "$0.00";
  return `$${num.toLocaleString("en-CA", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

// ─── Component ──────────────────────────────────────────────────────────────

export default function PayablesCSVBackfill() {
  const navigate = useNavigate();
  const { user, loading: authLoading, profile } = useAuth();
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Auth & loading
  const [pageState, setPageState] = useState<PageState>("upload");

  // Status counts from DB
  const [statusCounts, setStatusCounts] = useState<StatusCounts>({
    complete: 0,
    pending_ap_entry: 0,
    no_invoice_submitted: 0,
  });
  const [countsLoading, setCountsLoading] = useState(true);

  // File upload
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [csvText, setCsvText] = useState<string>("");
  const [fileError, setFileError] = useState<string>("");
  const [isDragging, setIsDragging] = useState(false);

  // Preview
  const [parsedRows, setParsedRows] = useState<ParsedCSVRow[]>([]);
  const [pendingInvoiceNumbers, setPendingInvoiceNumbers] = useState<
    Set<string>
  >(new Set());
  const [completeInvoiceNumbers, setCompleteInvoiceNumbers] = useState<
    Set<string>
  >(new Set());
  const [matchSummary, setMatchSummary] = useState<MatchSummary>({
    csvRowsFound: 0,
    willBeUpdated: 0,
    alreadyComplete: 0,
    notInDB: 0,
  });
  const [previewRows, setPreviewRows] = useState<PreviewRow[]>([]);

  // Confirm modal
  const [showConfirmModal, setShowConfirmModal] = useState(false);

  // Results
  const [backfillResult, setBackfillResult] = useState<BackfillResult | null>(
    null,
  );
  const [backfillError, setBackfillError] = useState<string>("");
  const [unmatchedOpen, setUnmatchedOpen] = useState(false);

  // ─── Auth guard ─────────────────────────────────────────────────────────
  useEffect(() => {
    if (!authLoading && !user) {
      navigate("/login");
    }
    if (!authLoading && profile && profile.role !== "admin") {
      navigate("/dashboard");
    }
  }, [authLoading, user, profile, navigate]);

  // ─── Fetch status counts ───────────────────────────────────────────────
  const fetchStatusCounts = useCallback(async () => {
    setCountsLoading(true);
    try {
      const [completeRes, pendingRes, uninvoicedRes] = await Promise.all([
        supabase
          .from("xtrf_payable_invoices")
          .select("*", { count: "exact", head: true })
          .eq("payable_status", "complete"),
        supabase
          .from("xtrf_payable_invoices")
          .select("*", { count: "exact", head: true })
          .eq("payable_status", "pending_ap_entry"),
        supabase
          .from("xtrf_payable_invoices")
          .select("*", { count: "exact", head: true })
          .eq("payable_status", "no_invoice_submitted"),
      ]);

      setStatusCounts({
        complete: completeRes.count ?? 0,
        pending_ap_entry: pendingRes.count ?? 0,
        no_invoice_submitted: uninvoicedRes.count ?? 0,
      });
    } catch (err) {
      console.error("Error fetching status counts:", err);
    } finally {
      setCountsLoading(false);
    }
  }, []);

  useEffect(() => {
    if (user) {
      fetchStatusCounts();
    }
  }, [user, fetchStatusCounts]);

  // ─── File handling ─────────────────────────────────────────────────────
  const handleFileSelect = useCallback(
    (file: File) => {
      setFileError("");

      if (!file.name.endsWith(".csv")) {
        setFileError("Please upload a .csv file");
        return;
      }

      setSelectedFile(file);

      const reader = new FileReader();
      reader.onload = (e) => {
        const text = e.target?.result as string;
        setCsvText(text);
      };
      reader.readAsText(file);
    },
    [],
  );

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleDrop = useCallback(
    (e: React.DragEvent) => {
      e.preventDefault();
      setIsDragging(false);
      const file = e.dataTransfer.files[0];
      if (file) handleFileSelect(file);
    },
    [handleFileSelect],
  );

  const handleInputChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) handleFileSelect(file);
    },
    [handleFileSelect],
  );

  // ─── Preview matches ──────────────────────────────────────────────────
  const handlePreviewMatches = useCallback(async () => {
    if (!csvText) return;

    const { rows, error } = parseCSV(csvText);
    if (error) {
      setFileError(error);
      return;
    }

    setParsedRows(rows);

    // Get unique invoice numbers from CSV
    const csvInvoiceNos = new Set(
      rows.map((r) => r.invoiceNo).filter(Boolean),
    );

    // Fetch pending AP entry records from DB
    const { data: pendingData } = await supabase
      .from("xtrf_payable_invoices")
      .select("invoice_final_number")
      .eq("payable_status", "pending_ap_entry");

    const pendingSet = new Set(
      (pendingData || []).map((r) => r.invoice_final_number).filter(Boolean),
    );
    setPendingInvoiceNumbers(pendingSet);

    // Fetch complete records to detect already-complete
    const { data: completeData } = await supabase
      .from("xtrf_payable_invoices")
      .select("invoice_final_number")
      .eq("payable_status", "complete");

    const completeSet = new Set(
      (completeData || []).map((r) => r.invoice_final_number).filter(Boolean),
    );
    setCompleteInvoiceNumbers(completeSet);

    // Build match summary
    let willBeUpdated = 0;
    let alreadyComplete = 0;
    let notInDB = 0;

    const seenInvoices = new Set<string>();

    for (const row of rows) {
      if (!row.invoiceNo || seenInvoices.has(row.invoiceNo)) continue;
      seenInvoices.add(row.invoiceNo);

      if (pendingSet.has(row.invoiceNo)) {
        willBeUpdated++;
      } else if (completeSet.has(row.invoiceNo)) {
        alreadyComplete++;
      } else {
        notInDB++;
      }
    }

    setMatchSummary({
      csvRowsFound: rows.length,
      willBeUpdated,
      alreadyComplete,
      notInDB,
    });

    // Build preview rows (first 10)
    const preview: PreviewRow[] = rows.slice(0, 10).map((row) => ({
      invoiceNo: row.invoiceNo,
      vendorName: row.vendorName,
      invoiceDate: row.invoiceDate,
      amountCAD: row.grossTotalCAD,
      matched: pendingSet.has(row.invoiceNo),
    }));
    setPreviewRows(preview);

    setPageState("preview");
  }, [csvText]);

  // ─── Run backfill ─────────────────────────────────────────────────────
  const handleRunBackfill = useCallback(async () => {
    setShowConfirmModal(false);
    setPageState("running");
    setBackfillError("");

    try {
      const {
        data: { session },
      } = await supabase.auth.getSession();

      const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
      const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

      const response = await fetch(
        `${supabaseUrl}/functions/v1/xtrf-csv-backfill`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${session?.access_token || supabaseAnonKey}`,
            "Content-Type": "text/plain",
          },
          body: csvText,
        },
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(errorText || `HTTP ${response.status}`);
      }

      const result: BackfillResult = await response.json();

      if (!result.success) {
        throw new Error(result.error || "Backfill returned unsuccessful");
      }

      setBackfillResult(result);
      setPageState("results");

      // Refresh status counts
      fetchStatusCounts();
    } catch (err: any) {
      if (
        err.name === "AbortError" ||
        err.message?.includes("timeout") ||
        err.message?.includes("network")
      ) {
        setBackfillError(
          "Request timed out \u2014 the backfill may still be running. Check the payables table.",
        );
      } else {
        setBackfillError(err.message || "An unknown error occurred");
      }
      setPageState("results");
    }
  }, [csvText, fetchStatusCounts]);

  // ─── Reset page ────────────────────────────────────────────────────────
  const handleReset = useCallback(() => {
    setPageState("upload");
    setSelectedFile(null);
    setCsvText("");
    setFileError("");
    setParsedRows([]);
    setMatchSummary({
      csvRowsFound: 0,
      willBeUpdated: 0,
      alreadyComplete: 0,
      notInDB: 0,
    });
    setPreviewRows([]);
    setBackfillResult(null);
    setBackfillError("");
    setUnmatchedOpen(false);
    if (fileInputRef.current) fileInputRef.current.value = "";
    fetchStatusCounts();
  }, [fetchStatusCounts]);

  // ─── Loading / guard ──────────────────────────────────────────────────
  if (authLoading) {
    return (
      <div className="flex h-screen items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-[#2E5FA3]" />
      </div>
    );
  }

  if (!user || (profile && profile.role !== "admin")) {
    return null;
  }

  // ─── Fields that will be filled table data ────────────────────────────
  const fieldsToFill = [
    { field: "invoice_internal_number", example: "2026/628" },
    { field: "invoice_date", example: "2026-02-28" },
    { field: "vendor_name", example: "Wissanu Boonmak" },
    { field: "payment_due_date", example: "2026-04-15" },
    { field: "invoice_status", example: "CONFIRMED" },
    { field: "amount_cad", example: "135.73" },
    { field: "payment_status", example: "NOT_PAID" },
    {
      field: "payable_status",
      example: "complete \u2190 set on match",
    },
  ];

  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar />
      <main className="flex-1 overflow-y-auto">
        <div className="max-w-6xl mx-auto px-6 py-8 space-y-6">
          {/* ─── SECTION 1: Page Header ─────────────────────────────── */}
          <div>
            <h1 className="text-2xl font-bold text-[#1F3864]">
              Payables CSV Backfill
            </h1>
            <p className="text-sm text-gray-500 mt-1">
              Upload the XTRF Vendor Invoice export to complete pending AP
              records
            </p>
          </div>

          {/* Status summary cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card>
              <CardContent className="flex items-center gap-3 p-4">
                <span className="text-2xl">&#x1F7E2;</span>
                <div>
                  <p className="text-sm text-gray-500">Complete</p>
                  <p className="text-2xl font-bold text-[#1F7A4F]">
                    {countsLoading ? (
                      <Loader2 className="h-5 w-5 animate-spin inline" />
                    ) : (
                      statusCounts.complete.toLocaleString()
                    )}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="flex items-center gap-3 p-4">
                <span className="text-2xl">&#x1F7E1;</span>
                <div>
                  <p className="text-sm text-gray-500">Pending AP Entry</p>
                  <p className="text-2xl font-bold text-[#C47B00]">
                    {countsLoading ? (
                      <Loader2 className="h-5 w-5 animate-spin inline" />
                    ) : (
                      statusCounts.pending_ap_entry.toLocaleString()
                    )}
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardContent className="flex items-center gap-3 p-4">
                <span className="text-2xl">&#x26AA;</span>
                <div>
                  <p className="text-sm text-gray-500">Uninvoiced</p>
                  <p className="text-2xl font-bold text-gray-500">
                    {countsLoading ? (
                      <Loader2 className="h-5 w-5 animate-spin inline" />
                    ) : (
                      statusCounts.no_invoice_submitted.toLocaleString()
                    )}
                  </p>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* ─── SECTION 2: Upload Zone ─────────────────────────────── */}
          {(pageState === "upload" || pageState === "preview") && (
            <Card>
              <CardContent className="p-6 space-y-4">
                {/* Drag & Drop zone */}
                <div
                  onClick={() => fileInputRef.current?.click()}
                  onDragOver={handleDragOver}
                  onDragLeave={handleDragLeave}
                  onDrop={handleDrop}
                  className={`
                    border-2 border-dashed rounded-lg p-10 text-center cursor-pointer transition-colors
                    ${isDragging ? "border-[#2E5FA3] bg-blue-50" : "border-gray-300 hover:border-[#2E5FA3] hover:bg-gray-50"}
                    ${selectedFile ? "border-[#1F7A4F] bg-green-50" : ""}
                  `}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    accept=".csv"
                    onChange={handleInputChange}
                    className="hidden"
                  />

                  {selectedFile ? (
                    <div className="flex items-center justify-center gap-3">
                      <FileCheck className="h-8 w-8 text-[#1F7A4F]" />
                      <div className="text-left">
                        <p className="font-medium text-[#1F3864]">
                          {selectedFile.name}
                        </p>
                        <p className="text-sm text-gray-500">
                          {(selectedFile.size / 1024).toFixed(1)} KB
                        </p>
                      </div>
                      <CheckCircle2 className="h-6 w-6 text-[#1F7A4F]" />
                    </div>
                  ) : (
                    <div className="space-y-2">
                      <Upload className="h-10 w-10 text-gray-400 mx-auto" />
                      <p className="text-gray-600">
                        Drop XTRF Vendor Invoice CSV here, or click to browse
                      </p>
                      <p className="text-xs text-gray-400">
                        Accepts .csv files only
                      </p>
                    </div>
                  )}
                </div>

                {/* File error */}
                {fileError && (
                  <Alert variant="destructive">
                    <AlertCircle className="h-4 w-4" />
                    <AlertTitle>Error</AlertTitle>
                    <AlertDescription>{fileError}</AlertDescription>
                  </Alert>
                )}

                {/* Preview Matches button */}
                <div className="flex items-center justify-between">
                  <p className="text-xs text-gray-400">
                    Export from XTRF: Accounting &gt; Vendor Invoices &gt;
                    Export CSV
                  </p>
                  <Button
                    onClick={handlePreviewMatches}
                    disabled={!selectedFile || !csvText}
                    className="bg-[#1F3864] hover:bg-[#2E5FA3]"
                  >
                    Preview Matches
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* ─── SECTION 3: Preview & Confirm ───────────────────────── */}
          {pageState === "preview" && (
            <div className="space-y-6">
              {/* 2-column summary */}
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
                {/* Left panel: Match Summary */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-lg font-semibold text-[#1F3864] mb-4">
                      Match Summary
                    </h3>
                    <div className="grid grid-cols-2 gap-3">
                      <Card>
                        <CardContent className="p-3 text-center">
                          <p className="text-2xl font-bold text-[#1F3864]">
                            {matchSummary.csvRowsFound.toLocaleString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            CSV Rows Found
                          </p>
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="p-3 text-center">
                          <p className="text-2xl font-bold text-[#1F7A4F]">
                            {matchSummary.willBeUpdated.toLocaleString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            Will Be Updated
                          </p>
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="p-3 text-center">
                          <p className="text-2xl font-bold text-gray-400">
                            {matchSummary.alreadyComplete.toLocaleString()}
                          </p>
                          <p className="text-xs text-gray-500">
                            Already Complete
                          </p>
                        </CardContent>
                      </Card>
                      <Card>
                        <CardContent className="p-3 text-center">
                          <p className="text-2xl font-bold text-[#C47B00]">
                            {matchSummary.notInDB.toLocaleString()}
                          </p>
                          <p className="text-xs text-gray-500">Not in DB</p>
                        </CardContent>
                      </Card>
                    </div>
                  </CardContent>
                </Card>

                {/* Right panel: Fields That Will Be Filled */}
                <Card>
                  <CardContent className="p-6">
                    <h3 className="text-lg font-semibold text-[#1F3864] mb-4">
                      Fields That Will Be Filled
                    </h3>
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Field</TableHead>
                          <TableHead>Example Value</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {fieldsToFill.map((f) => (
                          <TableRow key={f.field}>
                            <TableCell className="font-mono text-xs">
                              {f.field}
                            </TableCell>
                            <TableCell className="text-sm">
                              {f.example}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </CardContent>
                </Card>
              </div>

              {/* Sample Matches Table */}
              <Card>
                <CardContent className="p-6">
                  <h3 className="text-lg font-semibold text-[#1F3864] mb-4">
                    Sample Matches (first 10 rows)
                  </h3>
                  <div className="overflow-x-auto">
                    <Table>
                      <TableHeader>
                        <TableRow>
                          <TableHead>Invoice No.</TableHead>
                          <TableHead>Vendor Name</TableHead>
                          <TableHead>Invoice Date</TableHead>
                          <TableHead>Amount CAD</TableHead>
                          <TableHead>Status</TableHead>
                        </TableRow>
                      </TableHeader>
                      <TableBody>
                        {previewRows.map((row, idx) => (
                          <TableRow key={idx}>
                            <TableCell className="font-mono text-sm">
                              {row.invoiceNo || "\u2014"}
                            </TableCell>
                            <TableCell>{row.vendorName || "\u2014"}</TableCell>
                            <TableCell>{row.invoiceDate || "\u2014"}</TableCell>
                            <TableCell>
                              {row.amountCAD
                                ? formatCurrency(row.amountCAD)
                                : "\u2014"}
                            </TableCell>
                            <TableCell>
                              {row.matched ? (
                                <Badge className="bg-[#1F7A4F] text-white hover:bg-[#1F7A4F]">
                                  matched
                                </Badge>
                              ) : (
                                <Badge
                                  variant="secondary"
                                  className="bg-gray-200 text-gray-600"
                                >
                                  unmatched
                                </Badge>
                              )}
                            </TableCell>
                          </TableRow>
                        ))}
                      </TableBody>
                    </Table>
                  </div>
                </CardContent>
              </Card>

              {/* Confirm Button */}
              <div className="flex justify-end">
                <Button
                  size="lg"
                  onClick={() => setShowConfirmModal(true)}
                  disabled={matchSummary.willBeUpdated === 0}
                  className="bg-[#1F7A4F] hover:bg-[#186840] text-white text-base px-8"
                >
                  Run Backfill &mdash; Update{" "}
                  {matchSummary.willBeUpdated.toLocaleString()} Records
                </Button>
              </div>
            </div>
          )}

          {/* ─── Running state ──────────────────────────────────────── */}
          {pageState === "running" && (
            <Card>
              <CardContent className="p-12 text-center space-y-4">
                <Loader2 className="h-12 w-12 animate-spin text-[#2E5FA3] mx-auto" />
                <p className="text-lg font-medium text-[#1F3864]">
                  Running backfill... this may take 30&ndash;60 seconds
                </p>
                <p className="text-sm text-gray-500">
                  Please do not close this page
                </p>
              </CardContent>
            </Card>
          )}

          {/* ─── SECTION 4: Results ─────────────────────────────────── */}
          {pageState === "results" && (
            <div className="space-y-6">
              {/* Error alert */}
              {backfillError && (
                <Alert variant="destructive">
                  <AlertCircle className="h-4 w-4" />
                  <AlertTitle>Backfill Error</AlertTitle>
                  <AlertDescription>{backfillError}</AlertDescription>
                </Alert>
              )}

              {/* Result summary cards */}
              {backfillResult && (
                <>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <Card>
                      <CardContent className="flex items-center gap-3 p-4">
                        <CheckCircle2 className="h-8 w-8 text-[#1F7A4F]" />
                        <div>
                          <p className="text-sm text-gray-500">Updated</p>
                          <p className="text-2xl font-bold text-[#1F7A4F]">
                            {backfillResult.updated.toLocaleString()} records
                          </p>
                        </div>
                      </CardContent>
                    </Card>

                    <Card>
                      <CardContent className="flex items-center gap-3 p-4">
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <AlertTriangle className="h-8 w-8 text-[#C47B00] cursor-help" />
                          </TooltipTrigger>
                          <TooltipContent>
                            <p>
                              These invoice numbers were not found in the XTRF
                              AP export
                            </p>
                          </TooltipContent>
                        </Tooltip>
                        <div>
                          <p className="text-sm text-gray-500">Unmatched</p>
                          <p className="text-2xl font-bold text-[#C47B00]">
                            {backfillResult.unmatched.toLocaleString()} records
                          </p>
                        </div>
                      </CardContent>
                    </Card>

                    {backfillResult.errors > 0 && (
                      <Card>
                        <CardContent className="flex items-center gap-3 p-4">
                          <XCircle className="h-8 w-8 text-[#C00000]" />
                          <div>
                            <p className="text-sm text-gray-500">Errors</p>
                            <p className="text-2xl font-bold text-[#C00000]">
                              {backfillResult.errors.toLocaleString()}
                            </p>
                          </div>
                        </CardContent>
                      </Card>
                    )}
                  </div>

                  {/* Unmatched accordion */}
                  {backfillResult.unmatched_sample &&
                    backfillResult.unmatched_sample.length > 0 && (
                      <Collapsible
                        open={unmatchedOpen}
                        onOpenChange={setUnmatchedOpen}
                      >
                        <Card>
                          <CardContent className="p-4">
                            <CollapsibleTrigger asChild>
                              <Button
                                variant="ghost"
                                className="w-full flex items-center justify-between p-0 h-auto hover:bg-transparent"
                              >
                                <span className="text-sm font-medium text-[#1F3864]">
                                  View{" "}
                                  {backfillResult.unmatched_sample.length}{" "}
                                  unmatched invoice numbers
                                </span>
                                <ChevronDown
                                  className={`h-4 w-4 text-gray-500 transition-transform ${unmatchedOpen ? "rotate-180" : ""}`}
                                />
                              </Button>
                            </CollapsibleTrigger>
                            <CollapsibleContent className="mt-3">
                              <div className="bg-gray-50 rounded-md p-4 max-h-60 overflow-y-auto">
                                <div className="flex flex-wrap gap-2">
                                  {backfillResult.unmatched_sample.map(
                                    (inv) => (
                                      <Badge
                                        key={inv}
                                        variant="outline"
                                        className="font-mono text-xs"
                                      >
                                        {inv}
                                      </Badge>
                                    ),
                                  )}
                                </div>
                              </div>
                            </CollapsibleContent>
                          </CardContent>
                        </Card>
                      </Collapsible>
                    )}
                </>
              )}

              {/* Action buttons */}
              <div className="flex gap-3 justify-end">
                <Button variant="outline" onClick={handleReset}>
                  Upload Another CSV
                </Button>
                <Button
                  onClick={() => navigate("/xtrf-invoices")}
                  className="bg-[#1F3864] hover:bg-[#2E5FA3]"
                >
                  View Payables Table
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </div>
          )}
        </div>
      </main>

      {/* ─── Confirmation Modal ─────────────────────────────────────── */}
      <Dialog open={showConfirmModal} onOpenChange={setShowConfirmModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Backfill</DialogTitle>
            <DialogDescription>
              This will update{" "}
              <strong>
                {matchSummary.willBeUpdated.toLocaleString()} records
              </strong>{" "}
              in the payables database. This action cannot be automatically
              undone.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setShowConfirmModal(false)}
            >
              Cancel
            </Button>
            <Button
              onClick={handleRunBackfill}
              className="bg-[#1F7A4F] hover:bg-[#186840] text-white"
            >
              Confirm &amp; Run
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
